### Name : SUMIT JHA

#### BATCH DA (BATCH-A2)

Q1. Create the first numpy array of 1-D with values (1,2,3,0).
Create a second numpy array of 1-D with values (4,1,0, 6).
Perform following simple arithmetic operations on these two numpy arrays:
• Addition
• Subtraction
• Multiplication
• Division

In [69]:

import numpy as np

In [73]:
#Creating 1-D numpy array
#fna = first numpy array and sna = second numpy array
fna = np.array([1,2,3,0])
sna = np.array([4,1,0,6])


In [75]:
#addition
add= fna+sna
add

array([5, 3, 3, 6])

In [77]:
#Subtraction
sub = fna-sna
sub


array([-3,  1,  3, -6])

In [79]:
#multipication
multiply = fna * sna
multiply


array([4, 2, 0, 0])

In [81]:
#division
div = fna * sna
div

array([4, 2, 0, 0])

Q2. Create the first numpy array of random integers between 1-100 of 5 elements in 1-D.
Create second numpy array of 2-D for the same range of integers of shape 4*5.
Now perform following simple arithmetic operations on these two numpy arrays:
• Addition
• Subtraction

In [84]:
one_d_array= np.random.randint(1,100, size = 5)
one_d_array


array([20, 99, 83, 75, 12])

In [86]:
two_d_array = np.random.randint(1,100, size = (4,5))
two_d_array

array([[71, 86, 36, 66, 91],
       [17, 72, 87, 57, 38],
       [ 1, 53,  1, 42, 81],
       [33, 26, 92, 16,  3]])

In [88]:
#addition

add= one_d_array+two_d_array

add

array([[ 91, 185, 119, 141, 103],
       [ 37, 171, 170, 132,  50],
       [ 21, 152,  84, 117,  93],
       [ 53, 125, 175,  91,  15]])

In [90]:
#Subtraction
Sub= two_d_array-one_d_array
Sub

array([[ 51, -13, -47,  -9,  79],
       [ -3, -27,   4, -18,  26],
       [-19, -46, -82, -33,  69],
       [ 13, -73,   9, -59,  -9]])

Q3. Create a 3-D array of 27 random elements using random function of shape 3*3*3.
Now pull the following elements using indexing/slicing
• Third column of second 2-D array
• First and third row of first 2-D array
• Intersection of first row and third column in third 2-D array

In [139]:
array_3d = np.random.rand(3, 3, 3)
array_3d

array([[[0.13276167, 0.06136216, 0.29401163],
        [0.57103212, 0.57683654, 0.68396146],
        [0.63283513, 0.09100296, 0.06350801]],

       [[0.49272785, 0.59335678, 0.12201603],
        [0.38175284, 0.56256858, 0.53078376],
        [0.24424111, 0.31515558, 0.76856552]],

       [[0.02199774, 0.11632011, 0.82942547],
        [0.77544558, 0.27372003, 0.40438073],
        [0.58372377, 0.25862828, 0.1162732 ]]])

In [141]:

third_column_second_2d = array_3d[1][:, 2]
print( third_column_second_2d)

[0.12201603 0.53078376 0.76856552]


In [145]:
rows_first_third_first_2d = array_3d[0][[0, 2], :]
print(rows_first_third_first_2d)

[[0.13276167 0.06136216 0.29401163]
 [0.63283513 0.09100296 0.06350801]]


In [147]:
intersection = array_3d[2][0, 2]
print(intersection)

0.829425467074406


Q4. Create a 2-D numpy array of random integers between 1 to 100 with shape 5*4.
Now perform following operations:
• Print only the even numbers from this array
• Print only the odd numbers from this array
• Print row wise sum of all elements
• Print column wise sum of all elements
• Convert this 2-D array into 3-D array of shape 2*2*5

In [149]:
array_2d = np.random.randint(1, 101, size=(5, 4))
print(array_2d)

[[15 68 34  9]
 [32 38 40 57]
 [15 42 79 83]
 [69 47 16 50]
 [99  2 90  3]]


In [151]:
even_numbers = array_2d[array_2d % 2 == 0]
print(even_numbers)

[68 34 32 38 40 42 16 50  2 90]


In [153]:
odd_numbers = array_2d[array_2d % 2 != 0]
print(odd_numbers)

[15  9 57 15 79 83 69 47 99  3]


In [157]:
row_wise_sum = np.sum(array_2d, axis=1)
print(row_wise_sum)

[126 167 219 182 194]


In [159]:
array_3d = array_2d.reshape(2, 2, 5)
print(array_3d)

[[[15 68 34  9 32]
  [38 40 57 15 42]]

 [[79 83 69 47 16]
  [50 99  2 90  3]]]


Q5. Create a 2-D numpy array of random integers between 1 to 100 with shape 5*4. Now
perform following operations:
• Swap first row with third row
• Swap second column with fourth column.
• Replace the values less than 50 with zero.
• Convert this 2D array into 1-D array

In [111]:
# Create a 2D array with random integers from 1 to 100
array_2d = np.random.randint(1, 101, size=(5, 4))
print("Original 2D Array:\n", array_2d)

Original 2D Array:
 [[ 84   2   5  44]
 [ 67  63   2  50]
 [ 38  31 100  54]
 [ 75  86  60   9]
 [ 35   8   2  88]]


In [113]:
# Swap the first row with the third row
array_2d[[0, 2]] = array_2d[[2, 0]]
print("After swapping first and third row:\n", array_2d)

After swapping first and third row:
 [[ 38  31 100  54]
 [ 67  63   2  50]
 [ 84   2   5  44]
 [ 75  86  60   9]
 [ 35   8   2  88]]


In [115]:
# Swap the second column with the fourth column
array_2d[:, [1, 3]] = array_2d[:, [3, 1]]
print("After swapping second and fourth column:\n", array_2d)

After swapping second and fourth column:
 [[ 38  54 100  31]
 [ 67  50   2  63]
 [ 84  44   5   2]
 [ 75   9  60  86]
 [ 35  88   2   8]]


In [117]:
# Replace values less than 50 with zero
array_2d[array_2d < 50] = 0
print("After replacing values less than 50 with zero:\n", array_2d)

After replacing values less than 50 with zero:
 [[  0  54 100   0]
 [ 67  50   0  63]
 [ 84   0   0   0]
 [ 75   0  60  86]
 [  0  88   0   0]]


In [119]:
# Convert the 2D array into a 1D array
array_1d = array_2d.flatten()
print("Converted 1D Array:\n", array_1d)

Converted 1D Array:
 [  0  54 100   0  67  50   0  63  84   0   0   0  75   0  60  86   0  88
   0   0]


Q6. Explain the concept of stacking in numpy with examples. How is it di􀆯erent from
concatenation. Give any 3 di􀆯erences between them

1. Dimension Change:
Stacking creates a new axis, increasing the dimensionality of the resulting array, while concatenation preserves the original dimensionality. 
2. Joining Method:
Stacking joins arrays along a new axis, while concatenation joins arrays along an existing axis. 
3. Resulting Array:
Stacking results in a higher-dimensional array with a new axis, whereas concatenation results in a single, potentially larger array along an existing dimension. 